from dila2sql.monitoring import init_monitoring
init_monitoring()

raise Exception("test exception raised on purpose")
